#sudo: false

language: node_js

# verificar version a usar
node_js:
  - node

cache: yarn

jobs:
  include:
    - stage: test
      install:
        - yarn install
      script:
        - yarn test

stages:
  - name: test
    # type = pull_request | type push
    # if: type = pull_request AND branch = main
